name: GitHub Actions Demo
on: [push]
jobs:
  restore:
    runs-on: ubuntu-latest
    name: Restore
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
  test:
      runs-on: ubuntu-latest
      name: Testing
      needs: restore
      steps:
        - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
